### ISSUE TITLE
Purpose of the projetct

### ISSUE THREAD

**Issue by igor-raits** [RustRPM/cargo-rpm#10]
As you might know (or not), there is rust2rpm which is used by Fedora/Mageia/openSUSE for dealing with crates to package them as RPM.

So why there is a need to rewrite all that?

**Comment by tarcieri** [comment]
When I originally started working on this I hadn't heard of rust2rpm. However, I did post some thoughts about this to the Fedora Rust SIG list:

https://lists.fedoraproject.org/archives/list/rust@lists.fedoraproject.org/thread/O7WNVLL7DN3TED3EAVNG5OUZYYCIXTN7/

> I think rust2rpm might have slightly different goals though? Where cargo-rpm is designed to instrument a project to build RPMs using the cargo workflow, it seems rust2rpm is more targeted at retroactively building RPMs from crate releases.

In practice, my use of `cargo-rpm` is to use RPM as the only release mechanism for internal tools we've written in Rust. That is to say, we are not doing releases of these tools to crates.io whatsoever, nor do we intend for anyone outside our organization to consume them.

How I see the two projects:

- `rust2rpm`: convert existing crates released to crates.io into RPMs, useful for creating RPMs to be included in official registries
- `cargo-rpm`: build RPMs directly from Rust source code using the cargo workflow. useful for internal or otherwise "unofficial" registries

**Comment by tarcieri** [comment]
@ignatenkobrain all that said, I think it'd be great to find some way to share code, or at least align on things like how versions are mapped

**Comment by igor-raits** [comment]
> convert existing crates released to crates.io into RPMs

that was never the goal of project, I always wanted to support multiple registries and even non-registries

**Comment by tarcieri** [comment]
I'd be interested in looking into how `rust2rpm` could be fitted into this sort of workflow. At least upon my initial investigations I couldn't figure out how.

If `cargo-rpm` could merely handle things like being aware of Cargo concepts e.g. workflows, workspaces but use `rust2rpm` in some way to actually assemble the resulting RPM, I think that'd be great.
